### ISSUE TITLE
 [Bug] Cannot load 4.12.1 on ruby:3.0.0-alpine

### ISSUE THREAD

**Issue by aliismayilov** [appoptics/appoptics-apm-ruby#123] opened 2021-03-25 17:54 UTC
# Description

I load appoptics_apm gem (v4.12.1) on ruby 3 alpine image.

# How to reproduce or use case

This is the output when the gem is loaded:
```
E, [2021-03-25T17:52:48.659398 #3] ERROR -- : ==============================================================
E, [2021-03-25T17:52:48.659515 #3] ERROR -- : Missing AppOpticsAPM libraries.  Tracing disabled.
E, [2021-03-25T17:52:48.677270 #3] ERROR -- : Error: cannot load such file -- /vendor/ruby/3.0.0/gems/appoptics_apm-4.12.1/lib/oboe_metal.so
E, [2021-03-25T17:52:48.677390 #3] ERROR -- : See: https://docs.appoptics.com/kb/apm_tracing/ruby/
E, [2021-03-25T17:52:48.677439 #3] ERROR -- : ==============================================================
W, [2021-03-25T17:52:48.696019 #3]  WARN -- : ==============================================================
W, [2021-03-25T17:52:48.696125 #3]  WARN -- : AppOpticsAPM not loaded. Tracing disabled.
W, [2021-03-25T17:52:48.696174 #3]  WARN -- : There may be a problem with the service key or other settings.
W, [2021-03-25T17:52:48.696214 #3]  WARN -- : Please check previous log messages.
W, [2021-03-25T17:52:48.696251 #3]  WARN -- : ==============================================================
```

# OS, Ruby version, Gemfile, Gemfile.lock, log message ... (if relevant)
OS: ruby:3.0.0-alpine (Docker image)
Ruby version: 3.0.0p0
appoptics_apm: 4.12.1

**Comment by prettycoder** [comment] 2021-03-25 23:44
I'm just picked this up and will try to reproduce ... 

If you have a minute, could you run `gem install appoptics_apm --verbose` and send me the output, this could speed things up.

**Comment by prettycoder** [comment] 2021-03-25 23:47
actually what you posted in the other issue is good for now

**Comment by prettycoder** [comment] 2021-04-07 19:23
figured out this one ... because of a change with Kernel.open appoptics_apm <= 4.12.1 can only be installed with Ruby < 3.0.0
Can't fix, sorry ¯\\_(ツ)_/¯

**Comment by prettycoder** [comment] 2021-04-07 19:24
We are working on fixing 4.12.2, which can be installed with Ruby >= 3.0.0

**Comment by prettycoder** [comment] 2021-04-12 22:51
closing - thanks for reporting @aliismayilov

**Closed by prettycoder** 2021-04-12 22:51 UTC
